linters-settings:
  nlreturn:
    # Size of the block (including return statement that is still "OK")
    # so no return split required.
    # Default: 1
    block-size: 2
linters:
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - cyclop
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exportloopref
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gosec
    - mirror
    - misspell
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - tagalign
    - testifylint
    - tparallel
    - paralleltest
    - nosprintfhostport
    - usestdlibvars
    - whitespace
    - wrapcheck

issues:
  # exclude:  
  #   - _test\.go
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: pkg/client/packages\.go|internal/packages/packages\.go|pkg/client/version\.go|pkg/client/authentication\.go
      linters:
        - wrapcheck

